### ISSUE TITLE
Drop blockhash dependency

### ISSUE THREAD

**Issue by pwlmaciejewski** [pwlmaciejewski/imghash#17]
## Why

`blockhash-js` doesn't declare `png-js` nor `jpeg-js` in it's deps, that forces `imghash` to do it instead. Also, the maintainers of https://github.com/commonsmachinery/blockhash-js can't update the npm version of the library (no access).

## What

1) Either replace `blockhash-js` with something else or fork it & fix the issue
2) Remove `png-js` and `jpeg-js` from the deps.

## Notes

spin-off #16

**Comment by LinusU** [comment]
I was planing on ripping out the core of that library to a separate package, and then make a PR to them to use it.

If we then only use the core package, this package would also start working in the browser 🙌 since `@canvas/image` uses the native `Image` object in the browser, and since the core wouldn't have any file-system or other dependencies

**Comment by LinusU** [comment]
Said and done: https://github.com/commonsmachinery/blockhash-js/pull/24

**Comment by pwlmaciejewski** [comment]
Fixed in #20
